//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by KLinePrint.rc
//
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDR_POPUP_EDIT                  119
#define ID_STATUSBAR_PANE1              120
#define ID_STATUSBAR_PANE2              121
#define IDS_STATUS_PANE1                122
#define IDS_STATUS_PANE2                123
#define IDS_TOOLBAR_STANDARD            124
#define IDS_TOOLBAR_CUSTOMIZE           125
#define ID_VIEW_CUSTOMIZE               126
#define IDR_MAINFRAME                   128
#define IDR_MAINFRAME_256               129
#define IDR_KLinePrintTYPE              130
#define ID_WINDOW_MANAGER               131
#define IDS_WINDOWS_MANAGER             132
#define ID_VIEW_FILEVIEW                133
#define ID_VIEW_CLASSVIEW               134
#define ID_PROPERTIES                   135
#define ID_OPEN                         136
#define ID_OPEN_WITH                    137
#define ID_DUMMY_COMPILE                138
#define ID_CLASS_ADD_MEMBER_FUNCTION    139
#define ID_CLASS_ADD_MEMBER_VARIABLE    140
#define ID_CLASS_DEFINITION             141
#define ID_CLASS_PROPERTIES             142
#define ID_NEW_FOLDER                   143
#define ID_SORT_MENU                    144
#define ID_SORTING_GROUPBYTYPE          145
#define ID_SORTING_SORTALPHABETIC       146
#define ID_SORTING_SORTBYTYPE           147
#define ID_SORTING_SORTBYACCESS         148
#define ID_VIEW_OUTPUTWND               149
#define ID_VIEW_PROPERTIESWND           150
#define ID_SORTPROPERTIES               151
#define ID_PROPERTIES1                  152
#define ID_PROPERTIES2                  153
#define ID_EXPAND_ALL                   154
#define IDS_FILE_VIEW                   155
#define IDS_CLASS_VIEW                  156
#define IDS_OUTPUT_WND                  157
#define IDS_PROPERTIES_WND              158
#define IDI_FILE_VIEW                   161
#define IDI_FILE_VIEW_HC                162
#define IDI_CLASS_VIEW                  163
#define IDI_CLASS_VIEW_HC               164
#define IDI_OUTPUT_WND                  165
#define IDI_OUTPUT_WND_HC               166
#define IDI_PROPERTIES_WND              167
#define IDI_PROPERTIES_WND_HC           168
#define IDR_EXPLORER                    169
#define IDB_EXPLORER_24                 170
#define IDR_SORT                        171
#define IDB_SORT_24                     172
#define IDR_POPUP_SORT                  173
#define IDR_POPUP_EXPLORER              174
#define IDB_FILE_VIEW                   175
#define IDB_FILE_VIEW_24                176
#define IDB_CLASS_VIEW                  177
#define IDB_CLASS_VIEW_24               178
#define IDR_MENU_IMAGES                 179
#define IDB_MENU_IMAGES_24              180
#define ID_TOOLS_MACRO                  181
#define IDR_OUTPUT_POPUP                182
#define IDR_PROPERTIES                  183
#define IDB_PROPERTIES_HC               184
#define IDR_THEME_MENU                  200
#define ID_SET_STYLE                    201
#define ID_VIEW_APPLOOK_WIN_2000        210
#define ID_VIEW_APPLOOK_OFF_XP          211
#define ID_VIEW_APPLOOK_WIN_XP          212
#define ID_VIEW_APPLOOK_OFF_2003        213
#define ID_VIEW_APPLOOK_VS_2005         214
#define ID_VIEW_APPLOOK_OFF_2007_BLUE   215
#define ID_VIEW_APPLOOK_OFF_2007_BLACK  216
#define ID_VIEW_APPLOOK_OFF_2007_SILVER 217
#define ID_VIEW_APPLOOK_OFF_2007_AQUA   218
#define IDS_BUILD_TAB                   300
#define IDS_DEBUG_TAB                   301
#define IDS_FIND_TAB                    302
#define IDS_EXPLORER                    305
#define IDS_EDIT_MENU                   306
#define IDD_SEARCH_CONTRACT             310
#define IDR_HTML_SEARCHCONTRACTDIALOG   311
#define IDR_PLAYBACK                    312
#define IDD_TRADE                       313
#define IDD_PLAYBACK_CONF               314
#define IDD_TRADE_LOG                   315
#define IDC_COMBO_VAR_LIST              1000
#define IDC_EDIT_MORE_THAN              1001
#define IDC_CHECK_MORE_THAN             1002
#define IDC_CHECK_TOP_N                 1003
#define IDC_EDIT_TOPN                   1004
#define IDC_CHECK_HIGH_LOW_RANGE        1005
#define IDC_CHECK_OPEN_CLOSE_RANGE      1006
#define IDC_COMBO1                      1007
#define IDC_CHECK_GAP                   1010
#define IDC_CHECK_GAP_RANGE             1010
#define IDC_BUTTON_BUY                  1011
#define IDC_BUTTON_SELL                 1012
#define IDC_LIST_ACCOUNT                1013
#define IDC_EDIT_FEE                    1014
#define IDC_EDIT_MARGIN                 1015
#define IDC_EDIT_UNITS                  1016
#define IDC_EDIT_SLOTS                  1017
#define IDC_LIST_POSITION               1018
#define IDC_BUTTON_CLOSE                1019
#define IDC_BUTTON_REVERSE              1020
#define IDC_BUTTON_UPDATE_PARAM         1021
#define IDC_RADIO_SEQUENCE              1022
#define IDC_RADIO_RANDOM                1023
#define IDC_DATETIMEPICKER1             1024
#define IDC_DATETIMEPICKER_FROM         1024
#define IDC_DATETIMEPICKER2             1025
#define IDC_DATETIMEPICKER_TO           1025
#define IDC_CHECK1                      1026
#define IDC_CHECK_ALLWEEK               1026
#define IDC_CHECK2                      1027
#define IDC_CHECK_MONDAY                1027
#define IDC_CHECK3                      1028
#define IDC_CHECK_TUESDAY               1028
#define IDC_CHECK4                      1029
#define IDC_CHECK_WEDNESDAY             1029
#define IDC_CHECK5                      1030
#define IDC_CHECK_THURSDAY              1030
#define IDC_CHECK6                      1031
#define IDC_CHECK_FRIDAY                1031
#define IDC_CHECK7                      1032
#define IDC_CHECK9                      1034
#define IDC_CHECK10                     1035
#define IDC_CHECK11                     1036
#define IDC_CHECK12                     1037
#define IDC_EDIT1                       1038
#define IDC_EDIT_GAP                    1038
#define IDC_EDIT_DEFAULT_SLOTS          1038
#define IDC_CHECK13                     1039
#define IDC_CHECK_FLUNC_ABOVE           1039
#define IDC_EDIT2                       1040
#define IDC_EDIT_FLUNC_ABOVE            1040
#define IDC_EDIT_MAXLOSS                1040
#define IDC_CHECK14                     1041
#define IDC_CHECK_FLUNC_BELOW           1041
#define IDC_EDIT3                       1042
#define IDC_EDIT_FLUNC_BELOW            1042
#define IDC_EDIT_TIMESTOP               1042
#define IDC_EDIT_MAXOPENTIMES           1043
#define IDC_RADIO_1YEAR                 1044
#define IDC_EDIT_MAXLOSSPERDAY          1044
#define IDC_RADIO_HALFYEAR              1045
#define IDC_EDIT_MAXLOSSPERDAY2         1045
#define IDC_EDIT_NOSAMEDIROPEN          1045
#define IDC_RADIO_3MONTH                1046
#define IDC_RADIO_DATE_RANGE            1047
#define IDC_RADIO1                      1048
#define IDC_RADIO_ALLDATE               1048
#define IDC_TIMEPICKER_FROM             1049
#define IDC_TIMEPICKER_TO               1050
#define IDC_LIST_DATE                   1051
#define IDC_LIST_FILE                   1052
#define IDC_LIST4                       1053
#define IDC_LIST_LOG                    1053
#define IDC_EDIT_MAXPROFIT              1054
#define IDC_COMBO_LOGFILE               1055
#define IDC_STATIC_CAPITAL              1056
#define ID_32771                        32771
#define ID_SEARCH_CONTRACT              32772
#define ID_32773                        32773
#define ID_32774                        32774
#define ID_32775                        32775
#define ID_GEN_CAL                      32776
#define ID_LOAD_CAL                     32777
#define ID_GEN_DAYLINE                  32778
#define ID_PLAYBACK_BEGIN               32779
#define ID_PLAYBACK_REV                 32780
#define ID_PLAYBACK_FASTREV             32781
#define ID_PLAYBACK_PAUSE               32782
#define ID_PLAYBACK_FORWARD             32783
#define ID_PLAYBACK_FASTFW              32784
#define ID_PLAYBACK_END                 32785
#define ID_PLAYBACK_STOP                32786
#define ID_32787                        32787
#define ID_PLAYBACK_CONF                32788
#define ID_32789                        32789
#define ID_TRADE_LOG                    32790
#define ID_32791                        32791
#define ID_STRATEGY                     32792

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        317
#define _APS_NEXT_COMMAND_VALUE         32793
#define _APS_NEXT_CONTROL_VALUE         1057
#define _APS_NEXT_SYMED_VALUE           312
#endif
#endif
